// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
/* Author: [royrdev] */
BUILDIN_DEF(skillselectmenu,"*"),
BUILDIN_DEF(skillselectmenuarray,"r"),
BUILDIN_DEF(getskillname,"v"),
BUILDIN_DEF(getskilldesc,"v"),
BUILDIN_DEF(getplagiarizedskill,"?"),
BUILDIN_DEF(getplagiarizedskilllv,"?"),